### PR TITLE
feature: add leveldb engine for experiment

### PR DESCRIPTION
**Pull request by feifeiiiiiiiiiii**
Signed-off-by: qinpengfei <qinpengfei.2008@163.com>

add leveldb engine for experiment

### CODE REVIEW

**Comment by alash3al** [comment]
thanks @feifeiiiiiiiiiii 

I'm already developing a leveldb implementation and I found that goleveldb is better than badgerdb and boltdb in my local tests on a one million of values in a list, it was very fast, anyway I'll accept yours, and I'll focus on implementing the document based commands, but I've some questions:

- Regarding the `incr`, I think you should use `Lock()` instead of `RLock()`, because INCR should be atomic for both read & write, not just read.
- Why you use  `Rlock` everywhere, I think that it is not needed, do you have another opinion?
- For `MSet` & `Delete`, I think that you should use `leveldb.Batch`.
- For `Scan`, You forgot to check `IncludeOffset` attribute, that will till you whether to do another `iter.Next()` call if `includeOffset` is `false`.
- For `MGet` you have a duplicated `if err != nil`.

That is all for now, feel free to tell me your opinion.

**Comment by feifeiiiiiiiiiii** [comment]
@alash3al OK, I will to modify for you suggest

**Comment by feifeiiiiiiiiiii** [comment]
@alash3al pls review change

Thanks

**Comment by feifeiiiiiiiiiii** [comment]
@alash3al pls review change

Thanks

**Pull request merged**
